// Publications, newest first within each category.
// After editing, run `node scripts/build.mjs` to regenerate the pages.
window.PUBLICATIONS = [
  {
    slug: "admit",
    category: "Top Conferences",
    title: "ADMIT: Support-Gated Memory-Write Admission for Document QA Agents",
    venue: "NeurIPS 2026 (Main)",
    date: "Sep 2026",
    authorsHtml: "<strong>Joongmin Shin*</strong>, Gyuho Shim, Hyeonseok Moon, Jaehyung Seo",
    abstract: "ADMIT treats memory writes by document QA agents as an admission decision rather than a default side effect. Candidate memory entries are gated by whether they are supported by the document evidence the agent actually used, reducing unsupported or unsafe content that persists into later reasoning.",
    contribution: "Support-gated admission control that decides what a document QA agent is allowed to commit to memory.",
    role: "First Author",
    status: "Accepted",
    keywords: ["agent memory", "memory-write safety", "document QA"],
    linkPlaceholders: ["Paper coming soon", "Code coming soon", "arXiv coming soon"],
    venueBadge: {
      path: "Venue/NeurIPS2026.png",
      alt: "NeurIPS 2026 venue logo"
    },
    cardImage: {
      path: "Venue/NeurIPS2026.png",
      alt: "NeurIPS 2026 venue logo"
    },
    doi: "",
    arxiv: ""
  },
  {
    slug: "pilar",
    category: "Top Conferences",
    title: "PILAR: A Page-Grounded Unified Evidence Representation via an Entity-Linked Assertion Graph for Open-Domain QA Agents over Multimodal Document Corpora",
    venue: "EMNLP 2026 (Findings)",
    date: "Aug 2026",
    authorsHtml: "<strong>Joongmin Shin*</strong>, Gyuho Shim, Jung-Hun Lee, Jaehyung Seo",
    abstract: "Open-domain question answering (ODQA) over multimodal document corpora requires linking evidence scattered across text, tables, and figures. Existing systems often store these sources separately or retrieve only coarse pages, which weakens global evidence linking. We present PILAR, a page-grounded unified evidence representation instantiated as an entity-linked assertion graph. PILAR maps sentence-, table-, and figure-derived facts into a common assertion space and uses the graph as a controlled linking layer over robust page retrieval. In a shared-reader evaluation with four agent frameworks, fourteen retrieval backends, and two benchmarks, PILAR achieves the best end-to-end EM/ANLS. Gains are largest on compositional, cross-document, and multimodal questions, with a single-shot improvement of +1.6 EM over flat retrieval, rising to +2.9 on compositional and +5.9 on 3-hop questions. Ablations show that current gains are driven mainly by the text-instantiated slice of the framework, while visual assertions help only after locality-aware filtering. We therefore position PILAR as a unified evidence representation for multimodal ODQA rather than a standalone visual-reasoning module.",
    contribution: "Entity-linked assertion graphs unify text, tables, and figures into a single page-grounded evidence representation for open-domain multimodal QA agents.",
    role: "First Author",
    status: "Accepted",
    keywords: ["evidence graphs", "multimodal QA", "entity linking"],
    legacySlugs: ["under-review-evidence-graph"],
    linkPlaceholders: ["Paper coming soon"],
    venueBadge: {
      path: "Venue/EMNLP2026.png",
      alt: "EMNLP 2026 venue logo"
    },
    cardImage: {
      path: "Venue/EMNLP2026.png",
      alt: "EMNLP 2026 venue logo"
    },
    doi: "",
    arxiv: "2609.32895",
    codeUrl: "https://github.com/ShinJM-maker/PILAR",
    figure: {
      path: "paper_figure/PILAR_architecture.png",
      caption: "PILAR overview: offline construction of the entity-linked assertion graph (left, center) and online page retrieval with controlled graph linking (right)",
      sourcePdf: "paper_figure/PILAR_architecture.pdf"
    },
    sections: [
      { heading: "Method", html: "<p>PILAR converts sentence-, table-, and figure-derived evidence into one subject-predicate-object assertion space. Text blocks are converted into assertions directly; tables, charts, and figures are processed by a VLM over cropped regions together with OCR and caption text, and the resulting assertions are kept only if they are grounded in the corresponding crop. The corpus is then organized into four connected layers:</p><ul><li><strong>Entity layer</strong>: canonical entities and cross-document aliases.</li><li><strong>Assertion layer</strong>: normalized claims in subject-predicate-object form.</li><li><strong>Support layer</strong>: the text spans, table regions, figure crops, and captions that justify each claim.</li><li><strong>Provenance layer</strong>: document ID, page number, section path, and bounding box of each support.</li></ul><p>The entity and assertion layers provide global evidence linking across documents and modalities, while the support and provenance layers preserve the page context needed to verify each claim. At query time, a hybrid BM25 and dense page retriever produces a shortlist, and the graph acts as a controlled linking layer on top of it: it follows local continuity, canonical aliases, and entity-assertion-support links, and a relevance gate suppresses weak expansions. The result is returned to the agent as a single page-grounded evidence packet, so the same backend serves single-shot prompting, iterative query reformulation, and planner-executor agents.</p><figure class=\"paper-figure\"><a href=\"../paper_figure/PILAR_running_example.png\" target=\"_blank\" rel=\"noopener noreferrer\"><img src=\"../paper_figure/PILAR_running_example.png\" alt=\"Running example\" loading=\"lazy\" /></a><figcaption>Running example. A sentence defines when cold-start mode applies, a table lists the model-specific charging settings for BatteryPack-A, and a figure caption in a second document specifies that cold-start operation uses the reduced current. PILAR links these supports through the canonical entity BatteryPack-A and returns one page-grounded evidence packet.</figcaption></figure><figure class=\"paper-figure paper-figure-narrow\"><a href=\"../paper_figure/PILAR_retrieval_trace.png\" target=\"_blank\" rel=\"noopener noreferrer\"><img src=\"../paper_figure/PILAR_retrieval_trace.png\" alt=\"Query-driven retrieval trace\" loading=\"lazy\" /></a><figcaption>Query-driven retrieval trace. A query enters the base shortlist, seeds are matched against entity and assertion fields, the query classifier selects an expansion profile, and graph traversal collects a support neighborhood. The packet builder assembles the final token-budgeted packet for the reader.</figcaption></figure>" },
      { heading: "Results", html: "<p>All text-based and graph backends share the same BM25 and dense page retriever and the same reader (Qwen3-VL-8B); page-based multimodal methods keep their native retrieval and packing pipeline under the same reader and evaluation protocol. Each cell shows EM / ANLS.</p><div class=\"table-scroll\"><table class=\"results-table\"><thead><tr><th rowspan=\"2\">Backend</th><th colspan=\"4\">M3DocVQA (EM / ANLS)</th><th colspan=\"4\">Frames (EM / ANLS)</th></tr><tr><th>Naive RAG</th><th>ReAct</th><th>PlanRAG</th><th>AutoGen</th><th>Naive RAG</th><th>ReAct</th><th>PlanRAG</th><th>AutoGen</th></tr></thead><tbody><tr class=\"group\"><td colspan=\"9\">Text chunk-based RAG</td></tr><tr><td>Flat chunk</td><td>32.0 / 34.4</td><td>31.4 / 34.1</td><td>27.4 / 29.5</td><td>31.8 / 34.5</td><td>13.8 / 16.7</td><td>11.6 / 14.5</td><td>9.1 / 11.2</td><td>13.4 / 16.6</td></tr><tr><td>LumberChunker</td><td>31.2 / 33.6</td><td>30.0 / 32.6</td><td>26.4 / 28.2</td><td>31.0 / 33.4</td><td>13.2 / 16.1</td><td>11.4 / 13.8</td><td>9.0 / 11.2</td><td>13.0 / 15.8</td></tr><tr><td>Meta Chunker</td><td>31.0 / 33.4</td><td>29.8 / 32.4</td><td>26.4 / 28.0</td><td>31.0 / 33.4</td><td>13.0 / 15.9</td><td>11.2 / 13.6</td><td>8.8 / 11.0</td><td>12.8 / 15.6</td></tr><tr><td>Structural chunking</td><td>30.4 / 32.8</td><td>29.2 / 31.8</td><td>25.8 / 27.6</td><td>30.2 / 32.6</td><td>12.6 / 15.4</td><td>10.8 / 13.4</td><td>8.6 / 10.8</td><td>12.4 / 15.0</td></tr><tr class=\"group\"><td colspan=\"9\">Hierarchical / structure-aware retrieval</td></tr><tr><td>RAPTOR</td><td>31.4 / 33.8</td><td>30.2 / 32.8</td><td>26.6 / 28.4</td><td>31.2 / 33.6</td><td>13.0 / 15.9</td><td>11.2 / 13.8</td><td>8.8 / 11.0</td><td>12.8 / 15.6</td></tr><tr><td>MultiDocFusion</td><td>31.4 / 33.9</td><td>30.0 / 32.6</td><td>27.2 / 29.1</td><td>32.0 / 33.7</td><td>12.2 / 15.6</td><td>10.8 / 13.3</td><td>8.3 / 11.0</td><td>11.6 / 14.3</td></tr><tr class=\"group\"><td colspan=\"9\">Graph-augmented chunk retrieval</td></tr><tr><td>HopRAG</td><td>31.6 / 34.0</td><td>30.4 / 33.0</td><td>26.8 / 28.6</td><td>31.4 / 33.8</td><td>13.2 / 16.1</td><td>11.4 / 14.0</td><td>9.0 / 11.2</td><td>13.0 / 15.8</td></tr><tr class=\"group\"><td colspan=\"9\">Entity-KG GraphRAG</td></tr><tr><td>MS GraphRAG</td><td>32.2 / 34.6</td><td>29.8 / 32.5</td><td>26.6 / 28.6</td><td>31.2 / 34.0</td><td>13.6 / 16.3</td><td>11.2 / 13.8</td><td>9.3 / 11.1</td><td>13.0 / 16.0</td></tr><tr><td>LightRAG</td><td>31.6 / 34.2</td><td>31.0 / 33.5</td><td>26.4 / 28.5</td><td>31.6 / 34.3</td><td>12.6 / 15.5</td><td>11.4 / 13.9</td><td>9.1 / 11.4</td><td>13.6 / 16.0</td></tr><tr class=\"group\"><td colspan=\"9\">Page-level multimodal RAG</td></tr><tr><td>M3DocRAG</td><td>19.0 / 25.2</td><td>16.0 / 16.6</td><td>10.0 / 12.7</td><td>19.0 / 25.2</td><td>12.0 / 16.5</td><td>4.0 / 5.3</td><td>1.0 / 3.2</td><td>11.0 / 15.2</td></tr><tr><td>VDocRAG</td><td>20.4 / 26.6</td><td>17.2 / 17.6</td><td>10.8 / 13.4</td><td>20.4 / 26.6</td><td>12.4 / 17.1</td><td>4.2 / 5.4</td><td>1.0 / 3.4</td><td>11.4 / 15.6</td></tr><tr class=\"group\"><td colspan=\"9\">VLM-augmented page retrieval</td></tr><tr><td>SimpleDoc</td><td>24.0 / 28.7</td><td>29.0 / 33.2</td><td>20.0 / 22.9</td><td>24.0 / 29.6</td><td>13.0 / 19.5</td><td>7.0 / 14.0</td><td>6.0 / 10.7</td><td>11.0 / 18.0</td></tr><tr class=\"group\"><td colspan=\"9\">Multimodal GraphRAG</td></tr><tr><td>MoLoRAG</td><td>19.4 / 25.6</td><td>16.4 / 17.0</td><td>10.4 / 13.0</td><td>19.4 / 25.6</td><td>12.2 / 16.8</td><td>4.2 / 5.5</td><td>1.2 / 3.4</td><td>11.2 / 15.4</td></tr><tr class=\"group\"><td colspan=\"9\">Page-grounded unified evidence representation (ours)</td></tr><tr class=\"ours\"><td>PILAR</td><td>33.6 / 36.3</td><td>31.4 / 34.5</td><td>28.0 / 29.8</td><td>32.6 / 35.3</td><td>15.0 / 17.9</td><td>12.4 / 15.2</td><td>10.5 / 12.5</td><td>14.5 / 17.5</td></tr></tbody></table></div><p class=\"table-note\">Main comparison: fourteen backends across four agent frameworks on M3DocVQA and Frames.</p><ul><li>PILAR yields the strongest overall profile, with the clearest gains on M3DocVQA. The Naive RAG gain on M3DocVQA is significant (p = 0.048, paired approximate randomization), and pooling across agents remains significant (p = 0.019).</li><li>Against the strongest competitor in each subset (Naive RAG, M3DocVQA), PILAR improves compositional (+2.9 EM), two-document (+2.2), and multimodal (+1.4) questions, where support must be linked across pages or documents.</li><li>In the strict matched-interface ablation below, the text-only slice of PILAR provides the largest single gain (+1.2 EM over page-only retrieval). Visual assertions hurt in isolation but recover +0.4 EM once locality-aware filtering is added.</li></ul><div class=\"table-scroll\"><table class=\"results-table\"><thead><tr><th>Variant</th><th>Local</th><th>Text slice</th><th>Visual</th><th>Gate</th><th>EM</th><th>ANLS</th><th>ROUGE-L</th></tr></thead><tbody><tr class=\"group\"><td colspan=\"8\">Page-level baselines</td></tr><tr><td>Page-only retrieval</td><td>✗</td><td>✗</td><td>✗</td><td>✗</td><td>32.0</td><td>34.4</td><td>37.3</td></tr><tr><td>Page-only + local prior</td><td>✓</td><td>✗</td><td>✗</td><td>✗</td><td>32.4</td><td>35.6</td><td>38.6</td></tr><tr class=\"group\"><td colspan=\"8\">+ PILAR text-only slice</td></tr><tr><td>PILAR (text-only slice)</td><td>✗</td><td>✓</td><td>✗</td><td>✗</td><td>33.2</td><td>36.1</td><td>38.9</td></tr><tr><td>PILAR (text-only) + local</td><td>✓</td><td>✓</td><td>✗</td><td>✗</td><td>33.0</td><td>36.1</td><td>39.0</td></tr><tr class=\"group\"><td colspan=\"8\">+ Visual assertions</td></tr><tr><td>PILAR (text+visual slice)</td><td>✗</td><td>✓</td><td>✓</td><td>✗</td><td>32.8</td><td>35.6</td><td>38.2</td></tr><tr><td>PILAR (text+visual) + local</td><td>✓</td><td>✓</td><td>✓</td><td>✗</td><td>33.4</td><td>36.1</td><td>38.9</td></tr><tr class=\"ours\"><td>Final (+ gate)</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>33.6</td><td>36.3</td><td>39.1</td></tr></tbody></table></div><p class=\"table-note\">Strict matched-interface ablation (Naive RAG, M3DocVQA). All rows share the same reader, prompt, packet budget, and evaluation split.</p>" }
    ],
    bibtex: "@inproceedings{shin2026pilar,\n  title     = {{PILAR}: A Page-Grounded Unified Evidence Representation via an Entity-Linked Assertion Graph for Open-Domain {QA} Agents over Multimodal Document Corpora},\n  author    = {Shin, Joongmin and Shim, Gyuho and Lee, Jung-hun and Seo, Jaehyung},\n  booktitle = {Findings of the Association for Computational Linguistics: EMNLP 2026},\n  year      = {2026},\n  eprint    = {2609.32895},\n  archivePrefix = {arXiv}\n}"
  },
  {
    slug: "hikey",
    category: "Top Conferences",
    highlight: "Oral",
    title: "HiKEY: Hierarchical Multimodal Retrieval for Open-Domain Document Question Answering",
    venue: "ACL 2026 (Main)",
    date: "Mar 2026",
    authorsHtml: "<strong>Joongmin Shin*</strong>, Gyuho Shim, Jeongbae Park, Jaehyung Seo, Heuiseok Lim",
    abstract: "HiKEY introduces a hierarchical multimodal retrieval framework for open-domain document question answering. The system combines global routing, local ranking, and structured evidence assembly to improve retrieval quality across long and visually complex documents.",
    contribution: "Hierarchical retrieval for multimodal document QA with structured evidence assembly.",
    role: "First Author",
    status: "Accepted",
    keywords: ["hierarchical retrieval", "multimodal QA", "evidence assembly"],
    legacySlugs: ["acl-anonymous", "under-review-hierarchical-retrieval"],
    linkPlaceholders: ["Paper coming soon", "Code coming soon"],
    venueBadge: {
      path: "Venue/ACL2026.png",
      alt: "ACL 2026 Main venue badge"
    },
    doi: "",
    arxiv: "2605.29606",
    figure: {
      path: "paper_figure/HiKEY_architecture.png",
      caption: "HiKEY retrieval pipeline"
    }
  },
  {
    slug: "m3docdep",
    category: "Top Conferences",
    title: "M3DocDep: Multi-modal, Multi-page, Multi-document Dependency Chunking with Large Vision-Language Models",
    venue: "CVPR 2026 (Main)",
    date: "Feb 2026",
    authorsHtml: "<strong>Joongmin Shin*</strong>, Jeongbae Park, Jaehyung Seo, Heuiseok Lim",
    abstract: "This work uses large vision-language models to infer cross-page and cross-document dependency structures in complex unstructured inputs. The resulting structure-aware multimodal chunks improve evidence retrieval quality and downstream QA performance for retrieval-augmented pipelines.",
    contribution: "LVLM-based dependency chunking that reconstructs cross-page structure for long-document retrieval and QA.",
    role: "First Author",
    status: "Accepted",
    keywords: ["document structure", "LVLM", "chunking", "retrieval"],
    venueBadge: {
      path: "Venue/CVPR2026.png",
      alt: "CVPR 2026 Main venue badge"
    },
    doi: "",
    arxiv: "2605.18774",
    paperUrl: "https://openaccess.thecvf.com/content/CVPR2026/html/Shin_M3DocDep_Multi-modal_Multi-page_Multi-document_Dependency_Chunking_with_Large_Vision-Language_Models_CVPR_2026_paper.html",
    figure: {
      path: "paper_figure/M3DocDep_architecture_preview.png",
      caption: "M3DocDep architecture",
      sourcePdf: "paper_figure/M3DocDep_architecture.pdf"
    }
  },
  {
    slug: "multidocfusion",
    category: "Top Conferences",
    title: "MultiDocFusion: Hierarchical and Multimodal Chunking Pipeline for Enhanced RAG on Long Industrial Documents",
    venue: "EMNLP 2025 (Main)",
    date: "Aug 2025",
    authorsHtml: "<strong>Joongmin Shin*</strong>, Chanjun Park, Jeongbae Park, Jaehyung Seo, Heuiseok Lim",
    abstract: "MultiDocFusion combines vision parsing, OCR, and hierarchy reconstruction to preserve document structure during chunking. It improves retrieval quality for long and noisy inputs and provides stronger evidence composition for downstream QA.",
    contribution: "A hierarchical multimodal chunking pipeline that preserves layout and improves evidence composition in industrial RAG.",
    role: "First Author",
    status: "Published",
    keywords: ["hierarchical chunking", "multimodal", "RAG", "industrial"],
    venueBadge: {
      path: "Venue/EMNLP2025.png",
      alt: "EMNLP 2025 venue badge"
    },
    paperUrl: "https://aclanthology.org/2025.emnlp-main.1062/",
    doi: "10.18653/v1/2025.emnlp-main.1062",
    arxiv: "2604.12352",
    figure: {
      path: "paper_figure/MultiDocFusion_architecture.png",
      caption: "MultiDocFusion architecture"
    }
  },
  {
    slug: "styledfs",
    category: "Top Conferences",
    shortName: "StyleDFS",
    title: "Intelligent Predictive Maintenance RAG Framework for Power Plants: Enhancing QA with StyleDFS and Domain Specific Instruction Tuning",
    venue: "EMNLP 2024 (Industry Track)",
    date: "Oct 2024",
    authorsHtml: "Seongtae Hong*, <strong>Joongmin Shin*</strong>, Jaehyung Seo, Taemin Lee, Jeongbae Park, Cho Man Young, Byeongho Choi, Heuiseok Lim",
    abstract: "StyleDFS proposes structure-aware chunking for high-stakes industrial QA. The framework improves answer quality while meeting on-premise and privacy constraints in real deployment environments.",
    contribution: "Domain-specific RAG framework for scientific and industrial QA.",
    role: "Co-First Author",
    status: "Accepted",
    keywords: ["domain RAG", "industrial QA"],
    venueBadge: {
      path: "Venue/EMNLP2024.png",
      alt: "EMNLP 2024 venue badge"
    },
    paperUrl: "https://aclanthology.org/2024.emnlp-industry.61/",
    doi: "10.18653/v1/2024.emnlp-industry.61",
    arxiv: "",
    figure: {
      path: "paper_figure/StyleDFS_architecture_preview.png",
      caption: "StyleDFS architecture",
      sourcePdf: "paper_figure/StyleDFS_architecture.pdf"
    }
  },
  {
    slug: "ur-iclr-agentic-memory-utility",
    category: "Under Review",
    title: "Evaluating the Practical Utility of Agentic Memory",
    venue: "ICLR 2027",
    date: "",
    authorsHtml: "Anonymous (Under review)",
    role: "First Author",
    status: "Under Review",
    noDetail: true,
    doi: "",
    arxiv: ""
  },
  {
    slug: "ur-iclr-video-citation",
    category: "Under Review",
    title: "Citation Grounding for Video Question Answering",
    venue: "ICLR 2027",
    date: "",
    authorsHtml: "Anonymous (Under review)",
    role: "First Author",
    status: "Under Review",
    noDetail: true,
    doi: "",
    arxiv: ""
  },
  {
    slug: "under-review-consumed-evidence-audit",
    detailTitle: "Project PRISM",
    category: "Under Review",
    title: "Evidence Auditing and Support-Sensitive Evaluation for Multimodal QA",
    venue: "TACL",
    date: "",
    authorsHtml: "Anonymous (Under review)",
    abstract: "Anonymous manuscript on consumed-evidence auditing for multimodal QA.",
    contribution: "A matched-reader audit framework separates real evidence use from evaluation illusions in multimodal QA.",
    role: "First Author",
    status: "Under Review",
    keywords: ["evidence auditing", "multimodal QA", "evaluation"],
    doi: "",
    arxiv: ""
  },
  {
    slug: "under-review-error-propagation",
    detailTitle: "Project CASCADE",
    category: "Under Review",
    title: "Error Propagation Diagnostics for PDF-to-RAG Pipelines Across Representation Families",
    venue: "IEEE TPAMI",
    date: "",
    authorsHtml: "Anonymous (Under review)",
    abstract: "Anonymous manuscript on error propagation and recoverability in PDF-to-RAG pipelines.",
    contribution: "A matched-intervention diagnostic framework analyzing how upstream parsing uncertainty propagates across PDF-to-RAG representation families.",
    role: "First Author",
    status: "Under Review",
    keywords: ["error propagation", "PDF-to-RAG", "diagnostics"],
    doi: "",
    arxiv: ""
  },
  {
    slug: "korlex-embeddings",
    category: "Journals",
    title: "Distance Based Korean WordNet (alias. KorLex) Embedding Model",
    venue: "Applied Artificial Intelligence 38(1), Taylor & Francis",
    date: "Sep 2024",
    authorsHtml: "SeongReol Park*, Joongmin Shin, Sanghyun Cho, Hyuk-Chul Kwon, Jung-Hun Lee",
    abstract: "This paper maps KorLex lexical knowledge into vector space to inject graph-aware semantics into representation learning. The approach improves lexical similarity behavior compared with purely distributional baselines.",
    contribution: "Graph-aware lexical embedding model that injects structured knowledge into vector representations.",
    role: "Co-Author",
    status: "Published",
    keywords: ["knowledge graph", "embedding", "Korean NLP"],
    paperUrl: "https://www.tandfonline.com/doi/full/10.1080/08839514.2024.2398920",
    doi: "",
    arxiv: "",
    figure: {
      path: "paper_figure/Distance Based Korean WordNet(alias. KorLex) Embedding Model_architecture.png",
      caption: "KorLex embedding model architecture"
    }
  },
  {
    slug: "hybrid-reader-tables-text",
    category: "Journals",
    title: "Multi-Paragraph Machine Reading Comprehension with Hybrid Reader over Tables and Text",
    venue: "Applied Artificial Intelligence 38(1), Taylor & Francis",
    date: "Jun 2024",
    authorsHtml: "Sanghyun Cho*, SeongReol Park, Hye-Lynn Kim, Jung-Hun Lee, Joongmin Shin, Hyuk-Chul Kwon",
    abstract: "Research on a hybrid reader model capable of processing both text and tables, enabling effective handling of both types of data while maintaining the performance of existing pre-trained models.",
    contribution: "Hybrid reader model that jointly processes text and tables for multi-paragraph machine reading comprehension.",
    role: "Co-Author",
    status: "Published",
    keywords: ["table QA", "reading comprehension", "hybrid model"],
    paperUrl: "https://www.tandfonline.com/doi/full/10.1080/08839514.2024.2367820",
    doi: "",
    arxiv: "",
    figure: {
      path: "paper_figure/Multi-Paragraph Machine Reading Comprehension_architecture.png",
      caption: "Multi-Paragraph Machine Reading Comprehension architecture"
    }
  },
  {
    slug: "retrieval-generation-techniques-llms",
    category: "Domestic Conferences & Theses",
    title: "Search-Based Generation Techniques for Improving LLM Responses: A Comparative Study of Zero-shot and RAG on GPT-3.5 and GPT-4",
    venue: "KIICE 2023",
    award: "Outstanding Paper Award",
    date: "Oct 2023",
    authorsHtml: "<strong>Joongmin Shin*</strong>, SeongReol Park, Jung-Hun Lee",
    abstract: "A comparative study on zero-shot versus retrieval-augmented generation setups for GPT-3.5 and GPT-4. The analysis outlines reliability and practical implementation benefits of evidence-grounded generation.",
    contribution: "Comparative analysis of zero-shot vs. RAG for GPT models, demonstrating benefits of evidence-grounded generation.",
    role: "First Author",
    status: "Published",
    keywords: ["RAG", "LLM", "comparative study"],
    doi: "",
    arxiv: ""
  },
  {
    slug: "comparative-korean-llm-quality",
    category: "Domestic Conferences & Theses",
    title: "Comparative Analysis of Korean Quality in Large-Scale Language Models Based on Zero-Shot Learning",
    venue: "HCLT 2023",
    date: "Oct 2023",
    authorsHtml: "Yunah Huh, Aram So, Taemin Lee, Joongmin Shin, Heuiseok Lim",
    abstract: "Compared the performance of Korean-based LLMs and English-based LLMs on four KoBEST tasks to investigate whether language influences LLM performance. The results confirmed that adding prior knowledge about Korean affects LLM performance.",
    contribution: "Investigated language-specific influences on LLM performance across Korean benchmarks.",
    role: "Co-Author",
    status: "Published",
    keywords: ["Korean LLM", "zero-shot", "evaluation"],
    doi: "",
    arxiv: ""
  },
  {
    slug: "qa-pair-passage-rag",
    category: "Domestic Conferences & Theses",
    title: "QA Pair Passage RAG-based LLM Korean Chatbot Service",
    venue: "HCLT 2023",
    date: "Oct 2023",
    authorsHtml: "<strong>Joongmin Shin*</strong>, Jaewwok Lee, Kyungmin Kim, Heuiseok Lim",
    abstract: "This work introduces QA-pair passage construction for Korean retrieval-augmented chatbot systems. The method improves retrieval relevance and reduces hallucination in domain-specific conversational settings.",
    contribution: "QA-pair passage construction method for Korean RAG chatbots, reducing hallucination in domain-specific settings.",
    role: "First Author",
    status: "Published",
    keywords: ["RAG", "chatbot", "Korean NLP"],
    doi: "",
    arxiv: ""
  },
  {
    slug: "neural-symbolic-korean-dependency-parsing",
    shortName: "M.S. Thesis",
    shortVenue: "PNU 2023",
    category: "Domestic Conferences & Theses",
    title: "A Neural-Symbolic Model for Overcoming Deep Learning Limitations in Korean Dependency Parsing",
    venue: "Master's Thesis, Pusan National University",
    date: "Feb 2023",
    authorsHtml: "<strong>Joongmin Shin*</strong>, Hyuk-Chul Kwon",
    abstract: "Proposed and analyzed a novel neural-symbolic model that controls final probability values based on additional linguistic knowledge to overcome the limitations of overfitting and data scarcity issues arising from deep learning's dependence on datasets.",
    contribution: "Neural-symbolic parser integrating linguistic constraints to overcome deep learning limitations in dependency parsing.",
    role: "First Author",
    status: "Published",
    keywords: ["dependency parsing", "neural-symbolic", "Korean NLP"],
    doi: "",
    arxiv: ""
  },
  {
    slug: "edt5-embeddings",
    category: "Domestic Conferences & Theses",
    title: "EDT5: Proposed Embedding Model of T5 Encoder-Decoder Structure",
    venue: "KSC 2022",
    award: "Outstanding Paper Award",
    date: "Dec 2022",
    authorsHtml: "<strong>Joongmin Shin*</strong>, Jugyung Jung, Jung-Hun Lee, Sanghyun Cho, Minho Kim, Miyeon Kim, Hyuk-Chul Kwon",
    abstract: "Analyzed the structure of T5 and proposed a model architecture that uses both the encoder and decoder for embedding, moving beyond the previous approach that only utilized the encoder for embedding and fine-tuning.",
    contribution: "Proposed encoder-decoder embedding architecture for T5, improving upon encoder-only approaches.",
    role: "First Author",
    status: "Published",
    keywords: ["T5", "embedding", "encoder-decoder"],
    doi: "",
    arxiv: ""
  },
  {
    slug: "korean-table-mrc-generalization",
    category: "Domestic Conferences & Theses",
    title: "Evaluation of Generalization Performance in Korean Table Machine Reading Comprehension across Domain-Specific Datasets",
    venue: "KSC 2022",
    date: "Dec 2022",
    authorsHtml: "Hyelin Kim*, Sanghyun Cho, Joongmin Shin, Hyuk-Chul Kwon",
    abstract: "Identified the limitations of existing tabular machine reading comprehension models in domain generalization through cross-validation, highlighting the importance of constructing tabular datasets across diverse domains.",
    contribution: "Identified domain generalization limitations in tabular MRC models through cross-validation analysis.",
    role: "Co-Author",
    status: "Published",
    keywords: ["table QA", "generalization", "evaluation"],
    doi: "",
    arxiv: ""
  },
  {
    slug: "constraint-enhanced-dependency-parsing",
    shortName: "Neural-Symbolic Parsing",
    shortVenue: "HCLT 2022",
    category: "Domestic Conferences & Theses",
    title: "A Dependency Parsing Model with Reinforced Head-Dependent Constraint Rules: Combining Deep Learning and Linguistic Knowledge",
    venue: "HCLT 2022",
    award: "Outstanding Research Award",
    date: "Oct 2022",
    authorsHtml: "<strong>Joongmin Shin*</strong>, Hyuk-Chul Kwon",
    abstract: "Through data and error case analysis, expanded the neural symbolic model from two applied rules to 24, developing a state-of-the-art model.",
    contribution: "Expanded neural-symbolic constraint rules from 2 to 24, achieving state-of-the-art dependency parsing.",
    role: "First Author",
    status: "Published",
    keywords: ["dependency parsing", "linguistic constraints", "neural-symbolic"],
    doi: "",
    arxiv: ""
  },
  {
    slug: "ann-dependency-parsing-rules",
    category: "Domestic Conferences & Theses",
    title: "Rule-Augmented Neural Network-Based Dependency Parsing",
    venue: "KCC 2022",
    date: "Jun 2022",
    authorsHtml: "<strong>Joongmin Shin*</strong>, Sanghyun Cho, Bongwoo Nam, Hyuk-Chul Kwon",
    abstract: "Added a transformer layer to existing graph-based dependency parsing models to incorporate additional feature embeddings and address gradient vanishing issues. Proposed a method that controls the final classification probability values according to predefined rules.",
    contribution: "Transformer-augmented dependency parser with rule-based probability control for improved parsing accuracy.",
    role: "First Author",
    status: "Published",
    keywords: ["dependency parsing", "transformer", "rule-based"],
    doi: "",
    arxiv: ""
  },
  {
    slug: "continual-learning-korean-mrc",
    category: "Domestic Conferences & Theses",
    title: "Korean Machine Reading Comprehension Using Continual Learning",
    venue: "HCLT 2021",
    date: "Oct 2021",
    authorsHtml: "<strong>Joongmin Shin*</strong>, Sanghyun Cho, Hyuk-Chul Kwon",
    abstract: "Applied Continual Learning to Korean machine reading comprehension to address the issue of deep learning models losing information from previously learned models.",
    contribution: "Applied continual learning to Korean MRC, addressing catastrophic forgetting in sequential model training.",
    role: "First Author",
    status: "Published",
    keywords: ["continual learning", "reading comprehension", "Korean NLP"],
    doi: "",
    arxiv: ""
  }
];
