// Builds every HTML page of the site from the data files and _src/pages/*.html.
//
//   node scripts/build.mjs
//
// Sources of truth:
//   site-data.js          news, stats, research areas, patents, links
//   publications-data.js  publications (list page, home, detail pages)
//   projects-data.js      projects (list page, home, detail pages)
//   _src/pages/*.html     hand-written page bodies; {{tokens}} are filled in here
//
// Generated files carry a "Generated by scripts/build.mjs" comment; edit the sources instead.

import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED = "<!-- Generated by scripts/build.mjs. Edit the data files or _src/pages/ instead. -->";

function loadData(file, key) {
  const context = { window: {} };
  vm.createContext(context);
  vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), context, { filename: file });
  return context.window[key];
}

const SITE = loadData("site-data.js", "SITE");
const PUBLICATIONS = loadData("publications-data.js", "PUBLICATIONS");
const PROJECTS = loadData("projects-data.js", "PROJECTS");
const PROJECT_GROUPS = loadData("projects-data.js", "PROJECT_GROUPS");

// ── helpers ────────────────────────────────────────────────────────────────

const esc = (value = "") =>
  String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const stripTags = (value = "") => String(value).replace(/<[^>]*>/g, "").replace(/\s+/g, " ").trim();

function truncate(text, max = 160) {
  return text.length <= max ? text : `${text.slice(0, max - 1).trimEnd()}…`;
}

function listJoin(items) {
  if (items.length <= 2) return items.join(" and ");
  return `${items.slice(0, -1).join(", ")}, and ${items[items.length - 1]}`;
}

const encodePath = p => encodeURI(p).replace(/#/g, "%23");
const venueShort = venue => String(venue || "").replace(/\s*\(.*\)\s*$/, "");
const venueKind = venue => (String(venue || "").match(/\(([^)]*)\)\s*$/) || [])[1] || "";
const shortName = pub => pub.shortName || (pub.title.includes(":") ? pub.title.split(":")[0] : pub.title);
const isFirstAuthor = pub => /first/i.test(pub.role || "");

function write(relPath, content) {
  const file = path.join(root, relPath);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content.replace(/[ \t]+$/gm, ""));
}

// ── derived values ─────────────────────────────────────────────────────────

const topConference = PUBLICATIONS.filter(p => p.category === "Top Conferences");
const firstAuthorTop = topConference.filter(isFirstAuthor);
const firstAuthorVenues = [...new Set(firstAuthorTop.map(p => venueShort(p.venue).split(" ")[0]))];
const detailPubs = PUBLICATIONS.filter(p => !p.noDetail);
const pubBySlug = Object.fromEntries(PUBLICATIONS.map(p => [p.slug, p]));

// Paper figures get a small JPEG thumbnail for list pages and link previews.
// Papers without an architecture figure can set `cardImage` (e.g. a venue logo) for list pages.
function thumbnailFor(pub) {
  const image = pub.figure || pub.cardImage;
  if (!image?.path) return null;
  const rel = `paper_figure/thumbs/${pub.slug}.jpg`;
  const out = path.join(root, rel);
  const src = path.join(root, image.path);
  if (!fs.existsSync(out) || fs.statSync(out).mtimeMs < fs.statSync(src).mtimeMs) {
    fs.mkdirSync(path.dirname(out), { recursive: true });
    execFileSync("convert", [`${src}[0]`, "-resize", "1200x>", "-background", "white", "-alpha", "remove", "-flatten", "-strip", "-quality", "82", out]);
  }
  return rel;
}

// ── layout ─────────────────────────────────────────────────────────────────

const NAV = [
  { key: "home", label: "Home", href: "index.html" },
  { key: "about", label: "About", href: "about.html" },
  { key: "experience", label: "Experience", href: "experience.html" },
  { key: "projects", label: "Projects", href: "projects.html" },
  { key: "publications", label: "Publications", href: "publications.html" }
];

function layout({ path: pagePath, title, description, active, body, image, type = "website", head = "", scripts = [] }) {
  const depth = pagePath.split("/").length - 1;
  const up = "../".repeat(depth);
  const url = pagePath === "index.html" ? `${SITE.url}/` : `${SITE.url}/${pagePath}`;
  const ogImage = `${SITE.url}/${encodePath(image || "profile_picture.png")}`;
  const nav = NAV.map(item => {
    const current = item.key === active ? ' aria-current="page"' : "";
    return `        <a href="${up}${item.href}"${current}>${item.label}</a>`;
  }).join("\n");

  return `<!DOCTYPE html>
${GENERATED}
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}" />
  <link rel="canonical" href="${esc(url)}" />
  <meta property="og:type" content="${type}" />
  <meta property="og:title" content="${esc(title)}" />
  <meta property="og:description" content="${esc(description)}" />
  <meta property="og:url" content="${esc(url)}" />
  <meta property="og:image" content="${esc(ogImage)}" />
  <meta name="twitter:card" content="${image ? "summary_large_image" : "summary"}" />
  <meta name="theme-color" content="#8c1515" />
  <link rel="icon" href="${up}favicon.svg" type="image/svg+xml" />
  <link rel="stylesheet" href="${up}style.css" />
  <script>try{var t=localStorage.getItem("theme");if(t)document.documentElement.dataset.theme=t}catch(e){}</script>${head}
</head>
<body>
  <a class="skip-link" href="#main">Skip to content</a>
  <header class="site-header">
    <div class="container header-row">
      <a class="brand" href="${up}index.html">${esc(SITE.name)}</a>
      <nav class="site-nav" id="site-nav" aria-label="Primary">
${nav}
        <a href="${up}${SITE.links.cv}" target="_blank" rel="noopener noreferrer">CV</a>
      </nav>
      <div class="header-actions">
        <button class="theme-toggle" type="button" aria-label="Toggle dark mode"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/></svg></button>
        <button class="nav-toggle" type="button" aria-label="Open menu" aria-controls="site-nav" aria-expanded="false"><span></span><span></span><span></span></button>
      </div>
    </div>
  </header>
  <main id="main" class="container page">
${body.replace(/\s+$/, "")}
  </main>
  <footer class="site-footer">
    <div class="container footer-row">
      <p>&copy; ${new Date().getFullYear()} ${esc(SITE.name)}</p>
      <nav class="footer-links" aria-label="Elsewhere">
        <a href="mailto:${SITE.email}">Email</a>
        <a href="${SITE.links.scholar}" target="_blank" rel="noopener noreferrer">Scholar</a>
        <a href="${SITE.links.github}" target="_blank" rel="noopener noreferrer">GitHub</a>
        <a href="${SITE.links.linkedin}" target="_blank" rel="noopener noreferrer">LinkedIn</a>
      </nav>
    </div>
  </footer>
  <script src="${up}script.js" defer></script>${scripts.map(s => `\n  <script src="${up}${s}" defer></script>`).join("")}
</body>
</html>
`;
}

function redirect(target) {
  return `<!DOCTYPE html>
${GENERATED}
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="refresh" content="0; url=${esc(target)}" />
  <meta name="robots" content="noindex" />
  <title>Redirecting…</title>
  <script>window.location.replace(${JSON.stringify(target)}${target.includes("#") ? "" : " + window.location.hash"});</script>
</head>
<body>
  <p>Redirecting to <a href="${esc(target)}">${esc(target)}</a>.</p>
</body>
</html>
`;
}

// ── components ─────────────────────────────────────────────────────────────

function pubLinks(pub, up, { detail = true } = {}) {
  const links = [];
  if (pub.paperUrl) links.push(`<a href="${esc(pub.paperUrl)}" target="_blank" rel="noopener noreferrer">Paper</a>`);
  if (pub.doi) links.push(`<a href="https://doi.org/${esc(pub.doi)}" target="_blank" rel="noopener noreferrer">DOI</a>`);
  if (pub.arxiv) {
    const href = pub.arxiv.startsWith("http") ? pub.arxiv : `https://arxiv.org/abs/${pub.arxiv}`;
    links.push(`<a href="${esc(href)}" target="_blank" rel="noopener noreferrer">arXiv</a>`);
  }
  if (pub.codeUrl) links.push(`<a href="${esc(pub.codeUrl)}" target="_blank" rel="noopener noreferrer">Code</a>`);
  if (detail && !pub.noDetail) links.push(`<a href="${up}publications/${pub.slug}.html">Details</a>`);
  return links.length ? `<p class="pub-links">${links.join("")}</p>` : "";
}

function venueLine(pub) {
  const kind = venueKind(pub.venue);
  const parts = [`<span class="pub-venue">${esc(venueShort(pub.venue))}</span>`];
  if (kind) parts.push(esc(kind));
  if (pub.highlight) parts.push(`<span class="tag tag-accent">${esc(pub.highlight)}</span>`);
  return parts.join(" · ");
}

function pubFeature(pub, up) {
  const thumb = thumbnailFor(pub);
  const media = thumb
    ? `<img${pub.figure ? "" : ' class="pub-thumb-logo"'} src="${up}${encodePath(thumb)}" alt="${esc(pub.figure?.caption || pub.cardImage?.alt || `${shortName(pub)} overview`)}" loading="lazy" />`
    : `<span class="pub-thumb-fallback" aria-hidden="true"><strong>${esc(shortName(pub))}</strong>${esc(venueShort(pub.venue))}</span>`;
  const titleHtml = pub.noDetail ? esc(pub.title) : `<a href="${up}publications/${pub.slug}.html">${esc(pub.title)}</a>`;
  return `      <article class="pub-feature">
        <a class="pub-thumb${thumb ? "" : " pub-thumb-empty"}" href="${up}publications/${pub.slug}.html" tabindex="-1" aria-hidden="true">${media}</a>
        <div class="pub-body">
          <p class="pub-meta">${venueLine(pub)}</p>
          <h3 class="pub-title">${titleHtml}</h3>
          <p class="pub-authors">${pub.authorsHtml}</p>
          <p class="pub-summary">${esc(pub.contribution || "")}</p>
          ${pubLinks(pub, up, { detail: false })}
        </div>
      </article>`;
}

function pubCitation(pub, up) {
  const titleHtml = pub.noDetail ? esc(pub.title) : `<a href="${up}publications/${pub.slug}.html">${esc(pub.title)}</a>`;
  const meta = [esc(pub.venue), esc(pub.date)].filter(Boolean).join(" · ");
  return `        <li>
          <p class="cite-title">${titleHtml}</p>
          <p class="cite-authors">${pub.authorsHtml}</p>
          <p class="cite-meta">${meta}</p>
        </li>`;
}

function reviewItem(pub, up) {
  const titleHtml = pub.noDetail ? esc(pub.title) : `<a href="${up}publications/${pub.slug}.html">${esc(pub.title)}</a>`;
  return `        <li>
          <p class="cite-title">${titleHtml}</p>
          <p class="cite-meta">${esc(pub.venue)}${pub.contribution ? ` — ${esc(pub.contribution)}` : ""}</p>
        </li>`;
}

const components = {
  heroStats() {
    const items = [
      [firstAuthorTop.length, `first-author papers at ${listJoin(firstAuthorVenues)}`],
      [SITE.stats.groupPublications, "publications with KUDoc"],
      [SITE.stats.patents, "patents"],
      [SITE.stats.transfers, "technology transfers"],
      [SITE.stats.awards, "awards"]
    ];
    return `    <ul class="stats" aria-label="Highlights">
${items.map(([n, label]) => `      <li><strong>${n}</strong> ${esc(label)}</li>`).join("\n")}
    </ul>`;
  },

  news() {
    return `      <ol class="news">
${SITE.news.map(item => `        <li><span class="news-date">${esc(item.date)}</span><p>${item.html}</p></li>`).join("\n")}
      </ol>`;
  },

  selectedPublications() {
    return `      <div class="pub-features">
${topConference.map(p => pubFeature(p, "")).join("\n")}
      </div>`;
  },

  researchAreas() {
    return `      <div class="areas">
${SITE.researchAreas.map(area => `        <article class="area">
          <h3>${esc(area.title)}</h3>
          <p>${esc(area.text)}</p>
          <p class="area-pubs">${area.pubs.map(slug => {
            const pub = pubBySlug[slug];
            if (!pub) throw new Error(`Unknown publication slug in researchAreas: ${slug}`);
            return `<a href="publications/${slug}.html">${esc(shortName(pub))} <span>${esc(venueShort(pub.venue))}</span></a>`;
          }).join("")}</p>
        </article>`).join("\n")}
      </div>`;
  },

  projectGroups() {
    return `      <div class="areas">
${PROJECT_GROUPS.map(group => {
      const items = PROJECTS.filter(p => p.group === group.name);
      return `        <article class="area">
          <h3>${esc(group.name)} <span class="count">${items.length}</span></h3>
          <p class="area-pubs">${items.map(p => `<a href="projects/${p.slug}.html">${esc(p.cardTitle || p.title)}</a>`).join("")}</p>
        </article>`;
    }).join("\n")}
      </div>`;
  },

  publicationList() {
    const journals = PUBLICATIONS.filter(p => p.category === "Journals");
    const domestic = PUBLICATIONS.filter(p => p.category === "Domestic Conferences & Theses");
    const review = PUBLICATIONS.filter(p => p.category === "Under Review");
    const reviewFirst = review.filter(isFirstAuthor);
    const reviewCo = review.filter(p => !isFirstAuthor(p));
    const known = new Set([...topConference, ...journals, ...domestic, ...review]);
    const unknown = PUBLICATIONS.filter(p => !known.has(p));
    if (unknown.length) throw new Error(`Unknown publication category: ${unknown.map(p => p.slug).join(", ")}`);

    return `    <section class="section" id="conference" aria-labelledby="conference-title">
      <h2 class="section-title" id="conference-title">Conference Papers <span class="count">${topConference.length}</span></h2>
      <div class="pub-features">
${topConference.map(p => pubFeature(p, "")).join("\n")}
      </div>
    </section>

    <section class="section" id="journal" aria-labelledby="journal-title">
      <h2 class="section-title" id="journal-title">Journals <span class="count">${journals.length}</span></h2>
      <ol class="cite-list">
${journals.map(p => pubCitation(p, "")).join("\n")}
      </ol>
    </section>

    <section class="section" id="domestic" aria-labelledby="domestic-title">
      <h2 class="section-title" id="domestic-title">Domestic Conferences &amp; Theses <span class="count">${domestic.length}</span></h2>
      <ol class="cite-list">
${domestic.map(p => pubCitation(p, "")).join("\n")}
      </ol>
    </section>

    <section class="section" id="under-review" aria-labelledby="review-title">
      <h2 class="section-title" id="review-title">Manuscripts Under Review <span class="count">${review.length}</span></h2>
      <p class="section-lede">${reviewFirst.length} first-author and ${reviewCo.length} co-author manuscripts under peer review. Author lists are withheld under double-blind review.</p>
      <h3 class="subsection-title">First author</h3>
      <ul class="cite-list">
${reviewFirst.map(p => reviewItem(p, "")).join("\n")}
      </ul>
      <h3 class="subsection-title">Co-author</h3>
      <ul class="cite-list">
${reviewCo.map(p => reviewItem(p, "")).join("\n")}
      </ul>
    </section>

    <section class="section" id="patents" aria-labelledby="patents-title">
      <h2 class="section-title" id="patents-title">Patents <span class="count">${SITE.patents.length}</span></h2>
      <ul class="cite-list">
${SITE.patents.map(p => `        <li>
          <p class="cite-title">${esc(p.title)}</p>
          <p class="cite-meta">${esc(p.meta)}</p>
        </li>`).join("\n")}
      </ul>
      <p class="section-lede">${esc(SITE.researchDirections)}</p>
    </section>`;
  },

  projectList() {
    const listed = new Set();
    const sections = PROJECT_GROUPS.map(group => {
      const items = PROJECTS.filter(p => p.group === group.name);
      items.forEach(p => listed.add(p));
      const id = group.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
      return `    <section class="section" id="${id}" aria-labelledby="${id}-title">
      <h2 class="section-title" id="${id}-title">${esc(group.name)} <span class="count">${items.length}</span></h2>${group.intro ? `\n      <p class="section-lede">${esc(group.intro)}</p>` : ""}
      <div class="card-grid">
${items.map(projectCard).join("\n")}
      </div>
    </section>`;
    });
    const orphans = PROJECTS.filter(p => !listed.has(p));
    if (orphans.length) throw new Error(`Projects without a known group: ${orphans.map(p => p.slug).join(", ")}`);
    return sections.join("\n\n");
  }
};

function chips(project) {
  const list = [{ tone: "institution", text: project.cardAffiliation || project.affiliation }, ...(project.cardChips || [])];
  return list
    .filter(chip => chip && chip.text)
    .map(chip => `<span class="tag${chip.tone === "output" || chip.tone === "recognition" ? " tag-accent" : ""}">${esc(chip.text)}</span>`)
    .join("");
}

function projectCard(project) {
  return `        <a class="card" href="projects/${project.slug}.html">
          <span class="card-meta">${esc(project.period)}</span>
          <h3 class="card-title">${esc(project.cardTitle || project.title)}</h3>
          <p class="card-text">${esc(project.cardSummary || project.description || "")}</p>
          <span class="tags">${chips(project)}</span>
        </a>`;
}

// ── token filling for hand-written pages ───────────────────────────────────

const tokenContext = {
  ...SITE,
  firstAuthorCount: String(firstAuthorTop.length),
  firstAuthorVenues: listJoin(firstAuthorVenues)
};

function fillTokens(source, file) {
  return source.replace(/\{\{\s*([\w.]+)\s*\}\}/g, (match, key) => {
    if (components[key]) return components[key]();
    const value = key.split(".").reduce((obj, part) => (obj == null ? obj : obj[part]), tokenContext);
    if (value == null || typeof value === "object") throw new Error(`${file}: unknown token ${match}`);
    return esc(value);
  });
}

// ── pages ──────────────────────────────────────────────────────────────────

const PAGES = [
  {
    path: "index.html",
    active: "home",
    title: `${SITE.name} | Structure-Aware Multimodal Reasoning`,
    description: "Joongmin Shin researches structure-aware multimodal reasoning: recovering document structure to turn complex documents into auditable evidence for reliable retrieval, grounded generation, and long-context reasoning.",
    head: `
  <script type="application/ld+json">${JSON.stringify({
    "@context": "https://schema.org",
    "@type": "Person",
    name: SITE.name,
    url: `${SITE.url}/`,
    image: `${SITE.url}/profile_picture.png`,
    jobTitle: "Senior Researcher",
    worksFor: { "@type": "Organization", name: "Korea University" },
    sameAs: [SITE.links.scholar, SITE.links.github, SITE.links.linkedin],
    knowsAbout: ["Multimodal Reasoning", "Document Structure Recovery", "Retrieval-Augmented Generation", "Evidence Auditing", "Agent Memory"]
  })}</script>`
  },
  {
    path: "about.html",
    active: "about",
    title: `About | ${SITE.name}`,
    description: "From a Korean wrestling athlete to a multimodal reasoning researcher: the journey and research trajectory behind structured multimodal reasoning.",
    scripts: ["research-map.js"]
  },
  {
    path: "experience.html",
    active: "experience",
    title: `Experience | ${SITE.name}`,
    description: "Research and industry experience, education, awards, skills, and teaching of Joongmin Shin."
  },
  {
    path: "projects.html",
    active: "projects",
    title: `Projects | ${SITE.name}`,
    description: "Projects by Joongmin Shin spanning multimodal reasoning and document AI, foundation-model adaptation, and applied AI collaborations."
  },
  {
    path: "publications.html",
    active: "publications",
    title: `Publications | ${SITE.name}`,
    description: `Publications by Joongmin Shin, including ${firstAuthorTop.length} first-author papers at ${listJoin(firstAuthorVenues)}.`
  }
];

for (const page of PAGES) {
  const srcFile = `_src/pages/${page.path}`;
  let body;
  if (fs.existsSync(path.join(root, srcFile))) {
    body = fillTokens(fs.readFileSync(path.join(root, srcFile), "utf8"), srcFile);
  } else {
    throw new Error(`Missing ${srcFile}`);
  }
  write(page.path, layout({ ...page, body }));
}

function prevNext(list, index, base, label) {
  const prev = list[index - 1];
  const next = list[index + 1];
  const name = item => esc(item.detailTitle || item.cardTitle || item.title);
  return `      <nav class="pager" aria-label="${label} navigation">
        ${prev ? `<a href="${prev.slug}.html"><span>Previous</span>${name(prev)}</a>` : `<a href="../${base}"><span>Back</span>All ${label.toLowerCase()}s</a>`}
        ${next ? `<a class="pager-next" href="${next.slug}.html"><span>Next</span>${name(next)}</a>` : `<a class="pager-next" href="../${base}"><span>Back</span>All ${label.toLowerCase()}s</a>`}
      </nav>`;
}

detailPubs.forEach((pub, index) => {
  const title = pub.detailTitle || pub.title;
  const thumb = thumbnailFor(pub);
  const badge = pub.venueBadge?.path
    ? `<img class="venue-badge" src="../${encodePath(pub.venueBadge.path)}" alt="${esc(pub.venueBadge.alt || "Venue badge")}" />`
    : "";
  const figure = pub.figure?.path
    ? `
      <figure class="paper-figure">
        <a href="../${encodePath(pub.figure.sourcePdf || pub.figure.path)}" target="_blank" rel="noopener noreferrer"><img src="../${encodePath(thumb)}" alt="${esc(pub.figure.caption || "Architecture")}" /></a>
        <figcaption>${esc(pub.figure.caption || "Architecture")} — click to open the full-resolution figure.</figcaption>
      </figure>`
    : "";
  const keywords = pub.keywords?.length ? `\n      <p class="tags">${pub.keywords.map(k => `<span class="tag">${esc(k)}</span>`).join("")}</p>` : "";
  const body = `    <article class="detail">
      <p class="kicker"><a href="../publications.html">Publications</a> / ${esc(pub.category)}</p>
      <h1 class="detail-title">${esc(title)}</h1>
      <div class="detail-meta">${badge}<p>${venueLine(pub)}${pub.date ? ` · ${esc(pub.date)}` : ""}</p></div>
      <p class="detail-authors">${pub.authorsHtml || ""}</p>
      ${pubLinks(pub, "../", { detail: false })}${figure}
      <section class="detail-section">
        <h2>Abstract</h2>
        <p>${esc(pub.abstract || "Not specified yet.")}</p>
      </section>${pub.contribution ? `
      <section class="detail-section">
        <h2>Key Contribution</h2>
        <p>${esc(pub.contribution)}</p>
      </section>` : ""}${keywords}
${prevNext(detailPubs, index, "publications.html", "Publication")}
    </article>`;
  write(`publications/${pub.slug}.html`, layout({
    path: `publications/${pub.slug}.html`,
    active: "publications",
    type: "article",
    title: `${title} | ${SITE.name}`,
    description: truncate(stripTags([pub.abstract, venueShort(pub.venue)].filter(Boolean).join(" "))),
    image: thumb,
    body
  }));
  (pub.legacySlugs || []).forEach(alias => write(`publications/${alias}.html`, redirect(`${pub.slug}.html`)));
});

PROJECTS.forEach((project, index) => {
  const sections = [
    ["Description", project.description || "Not specified yet."],
    ["Role", project.role],
    ["Tools Used", project.tools],
    ["Achievements", project.achievements]
  ].filter(([, text]) => text);
  const body = `    <article class="detail">
      <p class="kicker"><a href="../projects.html">Projects</a> / ${esc(project.group)}</p>
      <h1 class="detail-title">${esc(project.title)}</h1>
      <div class="detail-meta"><p>${[project.period, project.affiliation].filter(Boolean).map(esc).join(" · ")}</p></div>
      <p class="tags">${chips({ ...project, cardAffiliation: null, affiliation: null })}</p>
${sections.map(([heading, text]) => `      <section class="detail-section">
        <h2>${heading}</h2>
        <p>${esc(text)}</p>
      </section>`).join("\n")}
${prevNext(PROJECTS, index, "projects.html", "Project")}
    </article>`;
  write(`projects/${project.slug}.html`, layout({
    path: `projects/${project.slug}.html`,
    active: "projects",
    type: "article",
    title: `${project.title} | ${SITE.name}`,
    description: truncate(stripTags([project.description, project.role, project.achievements].filter(Boolean).join(" "))),
    body
  }));
});

// Remove generated detail pages whose source entry no longer exists.
function pruneGenerated(dir, keep) {
  for (const name of fs.readdirSync(path.join(root, dir))) {
    if (!name.endsWith(".html") || keep.has(name)) continue;
    console.log(`Removing stale ${dir}/${name}`);
    fs.unlinkSync(path.join(root, dir, name));
  }
}

const keepPubs = new Set(detailPubs.flatMap(p => [`${p.slug}.html`, ...(p.legacySlugs || []).map(a => `${a}.html`)]));
const extraRedirects = SITE.redirects || {};
Object.keys(extraRedirects).filter(k => k.startsWith("publications/")).forEach(k => keepPubs.add(k.slice("publications/".length)));
pruneGenerated("publications", keepPubs);
pruneGenerated("projects", new Set(PROJECTS.map(p => `${p.slug}.html`)));

for (const [from, to] of Object.entries(extraRedirects)) write(from, redirect(to));

// Old query-string URLs (publication.html?slug=…, project.html?slug=…).
function queryRedirect(dir, slugs, fallback) {
  return `<!DOCTYPE html>
${GENERATED}
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="robots" content="noindex" />
  <title>Redirecting…</title>
  <script>
    var slugs = ${JSON.stringify(slugs)};
    var slug = new URLSearchParams(window.location.search).get("slug");
    window.location.replace(slugs.indexOf(slug) >= 0 ? "${dir}/" + slug + ".html" : "${fallback}");
  </script>
</head>
<body>
  <p>Redirecting to <a href="${fallback}">${fallback}</a>.</p>
</body>
</html>
`;
}
write("publication.html", queryRedirect("publications", [...keepPubs].map(n => n.replace(/\.html$/, "")), "publications.html"));
write("project.html", queryRedirect("projects", PROJECTS.map(p => p.slug), "projects.html"));

// ── sitemap ────────────────────────────────────────────────────────────────

const urls = [
  ...PAGES.map(p => (p.path === "index.html" ? "/" : `/${p.path}`)),
  ...detailPubs.map(p => `/publications/${p.slug}.html`),
  ...PROJECTS.map(p => `/projects/${p.slug}.html`)
];
write("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url><loc>${esc(SITE.url + u)}</loc></url>`).join("\n")}
</urlset>
`);

execFileSync(process.execPath, [path.join(root, "scripts/generate-record-markdown.mjs")], { stdio: "inherit" });

console.log(`Built ${PAGES.length} pages, ${detailPubs.length} publication pages, ${PROJECTS.length} project pages.`);
